"""add rag chunks vector storage

Revision ID: 40df9ce6820e
Revises: e5201130bf37
Create Date: 2026-09-27 02:51:55.466070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = '40df9ce6820e'
down_revision: Union[str, Sequence[str], None] = 'e5201130bf37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rag_chunks',
    sa.Column('chunk_id', sa.String(length=255), nullable=False),
    sa.Column('parent_page_id', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=100), nullable=False),
    sa.Column('document_id', sa.String(length=255), nullable=False),
    sa.Column('source_file', sa.String(length=500), nullable=False),
    sa.Column('page', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunking_strategy', sa.String(length=100), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('has_visual', sa.Boolean(), nullable=False),
    sa.Column('ocr_candidate', sa.Boolean(), nullable=False),
    sa.Column('rendered_page', sa.String(length=1000), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=False),
    sa.PrimaryKeyConstraint('chunk_id')
    )
    op.create_index(op.f('ix_rag_chunks_document_id'), 'rag_chunks', ['document_id'], unique=False)
    op.create_index(op.f('ix_rag_chunks_domain'), 'rag_chunks', ['domain'], unique=False)
    op.create_index(op.f('ix_rag_chunks_parent_page_id'), 'rag_chunks', ['parent_page_id'], unique=False)
    op.execute(
    """
    CREATE INDEX ix_rag_chunks_embedding_hnsw
    ON rag_chunks
    USING hnsw (embedding vector_cosine_ops)
    """
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rag_chunks_parent_page_id'), table_name='rag_chunks')
    op.drop_index(op.f('ix_rag_chunks_domain'), table_name='rag_chunks')
    op.drop_index(op.f('ix_rag_chunks_document_id'), table_name='rag_chunks')
    op.drop_table('rag_chunks')
    op.execute(
    """
    DROP INDEX IF EXISTS ix_rag_chunks_embedding_hnsw
    """
)
    # ### end Alembic commands ###
